name: Publish to Maven

on:
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and test with Gradle
        run: ./gradlew clean build test assemble publish jreleaserFullRelease

# TODO need priviliged CI to push to maven
# if master push to maven
#      - name: Publish to Maven
#        if: github.ref == 'refs/heads/master'
#        run: ./gradlew publish
#        env:
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}


# https://jreleaser.org/guide/latest/continuous-integration/github-actions.html
# ./gradlew jreleaserFullRelease